# Generated by Django 3.1 on 2020-10-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='satatus',
            new_name='status',
        ),
    ]
