# Generated by Django 3.1 on 2020-10-25 00:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20201022_0449'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
