# Generated by Django 3.1 on 2020-10-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_comentar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentar',
            new_name='Comentarios',
        ),
    ]
